CREATE TABLE pacientes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    telefone VARCHAR(15),
    data_nascimento DATE
);

CREATE TABLE fichas_anamnese (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    paciente_id BIGINT NOT NULL,
    endereco VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(50),
    cep VARCHAR(10),
    data_nascimento DATE,
    sexo VARCHAR(10),
    profissao VARCHAR(255),
    numero_contato VARCHAR(15),
    queixa_principal TEXT,
    costuma_ir_ao_podologo BOOLEAN,
    frequencia_podologo VARCHAR(50),
    faz_uso_de_medicamento BOOLEAN,
    qual_medicamento VARCHAR(255),
    alergico BOOLEAN,
    substancias_alergicas VARCHAR(255),
    posicao_trabalho VARCHAR(50),
    faz_uso_de_palmilha BOOLEAN,
    tipo_palmilha VARCHAR(50),
    fumante BOOLEAN,
    gestante BOOLEAN,
    amamentando BOOLEAN,
    pratica_atividade_fisica BOOLEAN,
    frequencia_atividade_fisica VARCHAR(50),
    esporte VARCHAR(50),
    tipo_calçado_esporte VARCHAR(50),
    tipo_calçado_diario VARCHAR(50),
    gestante_clinico BOOLEAN,
    hipertiroidismo BOOLEAN,
    renais BOOLEAN,
    quimioterapia_radioterapia BOOLEAN,
    osteoporose BOOLEAN,
    hipotiroidismo BOOLEAN,
    neuropatia BOOLEAN,
    antecedentes_oncologicos BOOLEAN,
    cardiopatia BOOLEAN,
    hipertensao BOOLEAN,
    reumatismo BOOLEAN,
    cirurgia_MMII BOOLEAN,
    marca_passo BOOLEAN,
    hipotensao BOOLEAN,
    alteracoes_vasculares BOOLEAN,
    diabetes BOOLEAN,
    taxa_glicemia VARCHAR(50),
    data_ultima_verificacao DATE,
    faz_uso_de_insulina BOOLEAN,
    dieta_hidrica BOOLEAN,
    dieta_alimentar BOOLEAN,
    cavo_supinado BOOLEAN,
    normal_neutro BOOLEAN,
    plano_pronado BOOLEAN,
    bromidrose BOOLEAN,
    isquemia BOOLEAN,
    calo_com_nucleo BOOLEAN,
    calo BOOLEAN,
    hidrose BOOLEAN,
    mal_perfurante BOOLEAN,
    psoriase BOOLEAN,
    verruga_plantar BOOLEAN,
    dedose_disedrose BOOLEAN,
    edema BOOLEAN,
    tungiase BOOLEAN,
    calosidade BOOLEAN,
    tinea BOOLEAN,
    fissuras BOOLEAN,
    dedos_rigidos BOOLEAN,
    dedos_espalmados BOOLEAN,
    martelo BOOLEAN,
    queda_de_metatarso BOOLEAN,
    onicoatrofia BOOLEAN,
    onicorrexe BOOLEAN,
    onicogrifose BOOLEAN,
    onicrocriptose BOOLEAN,
    granuloma BOOLEAN,
    onicolise BOOLEAN,
    onicofose BOOLEAN,
    onicomicose BOOLEAN,
    psoriase_ungueal BOOLEAN,
    perfusao VARCHAR(50),
    outras_alteracoes TEXT,
    rg_paciente VARCHAR(50),
    cpf_paciente VARCHAR(50),
    assinatura_paciente VARCHAR(255),
    FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE
);